server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: Admin123
  redis:
    host: 192.168.6.129
    port: 6379
    password: 101011
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mvc:
    servlet:
      load-on-startup: 1
mybatis-plus:
  type-aliases-package: com.zhn.entity # 别名扫描包
logging:
  level:
    com.zhn: debug
  pattern:
    dateformat: mm:ss.SSS